// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUiyPVw92U1Qfs7j5pWs2EtIMlaAZqQY',
    appId: '1:210383683572:android:27fd9da3a1f0ccab5a43a1',
    messagingSenderId: '210383683572',
    projectId: 'expense-tracker-4a1a0',
    storageBucket: 'expense-tracker-4a1a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOjs3HQWST5zSsDKKYpyUN2uZvBwfI-QQ',
    appId: '1:210383683572:ios:d48436991fd91a615a43a1',
    messagingSenderId: '210383683572',
    projectId: 'expense-tracker-4a1a0',
    storageBucket: 'expense-tracker-4a1a0.appspot.com',
    androidClientId: '210383683572-8n72d2uvgojts4bpi1os0739rqn8kbns.apps.googleusercontent.com',
    iosClientId: '210383683572-afk2bv06hq5ofqb0kvitp30ribjfus7k.apps.googleusercontent.com',
    iosBundleId: 'com.hamapp.monify',
  );
}
